# Generated by Django 5.0.7 on 2025-08-05 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursement_date', models.DateField()),
                ('first_repayment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off'), ('restructured', 'Restructured')], default='active', max_length=20)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('term_months', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('business', 'Business'), ('education', 'Education'), ('medical', 'Medical'), ('agriculture', 'Agriculture'), ('emergency', 'Emergency'), ('development', 'Development'), ('other', 'Other')], max_length=20)),
                ('purpose_description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('member_comments', models.TextField(blank=True, null=True)),
                ('staff_comments', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('application_form', 'Application Form'), ('guarantor_form', 'Guarantor Form'), ('collateral_document', 'Collateral Document'), ('approval_letter', 'Approval Letter'), ('disbursement_voucher', 'Disbursement Voucher'), ('loan_agreement', 'Loan Agreement'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='loan_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loan Document',
                'verbose_name_plural': 'Loan Documents',
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranteed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Guarantor',
                'verbose_name_plural': 'Loan Guarantors',
            },
        ),
        migrations.CreateModel(
            name='LoanTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topup_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_term_months', models.PositiveIntegerField()),
                ('new_monthly_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loan Top-up',
                'verbose_name_plural': 'Loan Top-ups',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interest_calculation_method', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance'), ('compound', 'Compound Interest')], default='reducing', max_length=20)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_term_months', models.PositiveIntegerField(default=1)),
                ('maximum_term_months', models.PositiveIntegerField(default=60)),
                ('processing_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('minimum_guarantors', models.PositiveIntegerField(default=1)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['name'],
            },
        ),
    ]
