# Generated by Django 5.0.7 on 2025-08-05 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='members.member'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='guarantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans', to='members.guarantor'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantors', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='new_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_source', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='original_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loan_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='loans.loantype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_loans', to='loans.loantype'),
        ),
        migrations.AlterUniqueTogether(
            name='loanguarantor',
            unique_together={('loan', 'guarantor')},
        ),
    ]
