# Generated by Django 5.0.7 on 2025-08-05 19:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('member_statement', 'Member Statement'), ('loan_statement', 'Loan Statement'), ('collection_report', 'Collection Report'), ('overdue_report', 'Overdue Report'), ('penalty_report', 'Penalty Report')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='repayment_reports/')),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_repayment_reports', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayment_reports', to='loans.loan')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayment_reports', to='members.member')),
            ],
            options={
                'verbose_name': 'Repayment Report',
                'verbose_name_plural': 'Repayment Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Repayment Schedule',
                'verbose_name_plural': 'Repayment Schedules',
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='RepaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Phone Call'), ('visit', 'Physical Visit')], max_length=20)),
                ('message', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
                ('repayment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='repayments.repaymentschedule')),
            ],
            options={
                'verbose_name': 'Repayment Reminder',
                'verbose_name_plural': 'Repayment Reminders',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_overdue', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('waived', 'Waived'), ('reversed', 'Reversed')], default='applied', max_length=20)),
                ('applied_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_penalties', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_transactions', to='loans.loan')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL)),
                ('repayment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='repayments.repaymentschedule')),
            ],
            options={
                'verbose_name': 'Penalty Transaction',
                'verbose_name_plural': 'Penalty Transactions',
            },
        ),
        migrations.CreateModel(
            name='RepaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('cash', 'Cash Payment'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('mpesa', 'M-Pesa'), ('bank_deposit', 'Bank Deposit'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('value_date', models.DateField(default=datetime.date.today)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_transactions', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='members.member')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repayment Transaction',
                'verbose_name_plural': 'Repayment Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='EarlyRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('proposed_payment_date', models.DateField()),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('early_settlement_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_settlement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_repayments', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_early_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_repayments', to='loans.loan')),
                ('settlement_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_settlement', to='repayments.repaymenttransaction')),
            ],
            options={
                'verbose_name': 'Early Repayment',
                'verbose_name_plural': 'Early Repayments',
            },
        ),
    ]
